# Site settings
name: ASCII Farm
title: ASCII Farm
url: "www.asciifarm.com"
baseurl: "/asciiFarm"
description: A place for Joel

twitter_username: Frozenfire92
github_username:  Frozenfire92

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

# Build settings
markdown: kramdown
